server:
  port: 8010

security:
  whitelist:
    - /users/auth/**
    - /actuator/**
    - /users/v3/api-docs

springdoc:
  api-docs:
    path: /users/v3/api-docs

spring:
  application:
    name: users-service
  datasource:
    hikari:
      connection-init-sql: set search_path to users_schema
  jpa:
    properties:
      hibernate:
        default_schema: users_schema