server:
  port: 8010

security:
  whitelist:
    - /users/auth/**
    - /actuator/**
    - /users/v3/api-docs

springdoc:
  api-docs:
    path: /users/v3/api-docs

spring:
  application:
    name: users-service
  datasource:
    url: jdbc:postgresql://postgres-users-service:5432/users_db