spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:.env
  datasource:
    url: jdbc:postgresql://localhost:5433/social_dating_db
  kafka:
    bootstrap-servers: localhost:9093